import { Injectable } from "@angular/core";
import { BehaviorSubject } from "rxjs";
@Injectable({
  providedIn: "root",
})
export class AuthStateService {
  private licenses$ = new BehaviorSubject<any>([
    {
      license_name: "Novice-Vendor-Lite",
      monthly_price: 180.0,
      annual_price: 2160.0,
      annual_advance_payment: 1944.0,
      number_of_stores: "Single store",
      number_of_products: 5,
      number_of_users: 1,
      features: [
        "24/7 SUPPORT",
        "SALES CHANNELS",
        "PROMOTIONS (Market Places, Google Ads, Social Media",
        "BILL OF MATERIAL CONFIGURATOR",
        "DELIVERY COMFIRMATION",
        "ORDER FULFILMENT",
        "SALES CAMPAIGN",
        "DISCOUNT VOUCHER",
        "CHECKOUT PAYMENT SYSTEM",
        "SSL CERTIFICATE",
        "ABANDONED CART RECOVERY*",
        "PROFESSIONAL REPORTS",
        "THIRD-PARTY CALCULATED SHIPPING RATES",
        "Show calculated rates with your own account or third-party couriers",
      ],
      transaction_percentage: {
        cartalist: 1.2,
        payment_gateway: 5,
      },
    },
    {
      license_name: "Novice-Vendor-Premium",
      monthly_price: 270.0,
      annual_price: 3564.0,
      annual_advance_payment: 3207.6,
      number_of_stores: "Single store",
      number_of_products: 25,
      number_of_users: 2,
      features: [
        "24/7 SUPPORT",
        "SALES CHANNELS",
        "PROMOTIONS (Market Places, Google Ads, Social Media",
        "BILL OF MATERIAL CONFIGURATOR",
        "DELIVERY COMFIRMATION",
        "ORDER FULFILMENT",
        "SALES CAMPAIGN",
        "DISCOUNT VOUCHER",
        "CHECKOUT PAYMENT SYSTEM",
        "SSL CERTIFICATE",
        "ABANDONED CART RECOVERY*",
        "PROFESSIONAL REPORTS",
        "THIRD-PARTY CALCULATED SHIPPING RATES",
        "Show calculated rates with your own account or third-party couriers",
      ],
      transaction_percentage: {
        cartalist: 1.2,
        payment_gateway: 5,
      },
    },
    {
      license_name: "Novice-Vendor-Alist",
      monthly_price: 360.0,
      annual_price: 4752.0,
      annual_advance_payment: 4276.8,
      number_of_stores: "Single store",
      number_of_products: 50,
      number_of_users: 5,
      features: [
        "24/7 SUPPORT",
        "SALES CHANNELS",
        "PROMOTIONS (Market Places, Google Ads, Social Media",
        "BILL OF MATERIAL CONFIGURATOR",
        "DELIVERY COMFIRMATION",
        "ORDER FULFILMENT",
        "SALES CAMPAIGN",
        "DISCOUNT VOUCHER",
        "CHECKOUT PAYMENT SYSTEM",
        "SSL CERTIFICATE",
        "ABANDONED CART RECOVERY*",
        "PROFESSIONAL REPORTS",
        "THIRD-PARTY CALCULATED SHIPPING RATES",
        "Show calculated rates with your own account or third-party couriers",
      ],
      transaction_percentage: {
        cartalist: 1.2,
        payment_gateway: 5,
      },
    },
    {
      license_name: "Start-Up",
      monthly_price: 1800.0,
      annual_price: 23760.0,
      annual_advance_payment: 21384.0,
      number_of_stores: "Two stores",
      number_of_products: 75,
      number_of_users: 20,
      features: [
        "24/7 SUPPORT",
        "SALES CHANNELS",
        "PROMOTIONS (Market Places, Google Ads, Social Media",
        "BILL OF MATERIAL CONFIGURATOR",
        "DELIVERY COMFIRMATION",
        "ORDER FULFILMENT",
        "SALES CAMPAIGN",
        "DISCOUNT VOUCHER",
        "CHECKOUT PAYMENT SYSTEM",
        "SSL CERTIFICATE",
        "ABANDONED CART RECOVERY*",
        "PROFESSIONAL REPORTS",
        "THIRD-PARTY CALCULATED SHIPPING RATES",
        "Show calculated rates with your own account or third-party couriers",
      ],
      transaction_percentage: {
        cartalist: 1.2,
        payment_gateway: 5,
      },
    },
    {
      license_name: "Start-Up-Premium",
      monthly_price: 3600.0,
      annual_price: 47520.0,
      annual_advance_payment: 42768.0,
      number_of_stores: "Two stores",
      number_of_products: 500,
      number_of_users: 40,
      features: [
        "24/7 SUPPORT",
        "SALES CHANNELS",
        "PROMOTIONS (Market Places, Google Ads, Social Media",
        "BILL OF MATERIAL CONFIGURATOR",
        "DELIVERY COMFIRMATION",
        "ORDER FULFILMENT",
        "SALES CAMPAIGN",
        "DISCOUNT VOUCHER",
        "CHECKOUT PAYMENT SYSTEM",
        "SSL CERTIFICATE",
        "ABANDONED CART RECOVERY*",
        "PROFESSIONAL REPORTS",
        "THIRD-PARTY CALCULATED SHIPPING RATES",
        "Show calculated rates with your own account or third-party couriers",
      ],
      transaction_percentage: {
        cartalist: 1.2,
        payment_gateway: 5,
      },
    },
    {
      license_name: "Start-Up-Advance",
      monthly_price: 9000.0,
      annual_price: 118800.0,
      annual_advance_payment: 106920.0,
      number_of_stores: "Multi stores",
      number_of_products: 2500,
      number_of_users: 100,
      features: [
        "24/7 SUPPORT",
        "SALES CHANNELS",
        "PROMOTIONS (Market Places, Google Ads, Social Media",
        "BILL OF MATERIAL CONFIGURATOR",
        "DELIVERY COMFIRMATION",
        "ORDER FULFILMENT",
        "SALES CAMPAIGN",
        "DISCOUNT VOUCHER",
        "CHECKOUT PAYMENT SYSTEM",
        "SSL CERTIFICATE",
        "ABANDONED CART RECOVERY*",
        "PROFESSIONAL REPORTS",
        "THIRD-PARTY CALCULATED SHIPPING RATES",
        "Show calculated rates with your own account or third-party couriers",
      ],
      transaction_percentage: {
        cartalist: 1.2,
        payment_gateway: 5,
      },
    },
    {
      license_name: "Start-Up-Alist",
      monthly_price: 18000.0,
      annual_price: 237600.0,
      annual_advance_payment: 213840.0,
      number_of_stores: "Multi stores",
      number_of_products: 5000,
      number_of_users: 200,
      features: [
        "24/7 SUPPORT",
        "SALES CHANNELS",
        "PROMOTIONS (Market Places, Google Ads, Social Media",
        "BILL OF MATERIAL CONFIGURATOR",
        "DELIVERY COMFIRMATION",
        "ORDER FULFILMENT",
        "SALES CAMPAIGN",
        "DISCOUNT VOUCHER",
        "CHECKOUT PAYMENT SYSTEM",
        "SSL CERTIFICATE",
        "ABANDONED CART RECOVERY*",
        "PROFESSIONAL REPORTS",
        "THIRD-PARTY CALCULATED SHIPPING RATES",
        "Show calculated rates with your own account or third-party couriers",
      ],
      transaction_percentage: {
        cartalist: 1.2,
        payment_gateway: 5,
      },
    },
    {
      license_name: "Start-Up-Alist",
      monthly_price: 36000.0,
      annual_price: 475200.0,
      annual_advance_payment: 427680.0,
      number_of_stores: "Multi stores",
      number_of_products: "unlimited",
      number_of_users: "unlimited",
      features: [
        "24/7 SUPPORT",
        "SALES CHANNELS",
        "PROMOTIONS (Market Places, Google Ads, Social Media",
        "BILL OF MATERIAL CONFIGURATOR",
        "DELIVERY COMFIRMATION",
        "ORDER FULFILMENT",
        "SALES CAMPAIGN",
        "DISCOUNT VOUCHER",
        "CHECKOUT PAYMENT SYSTEM",
        "SSL CERTIFICATE",
        "ABANDONED CART RECOVERY*",
        "PROFESSIONAL REPORTS",
        "THIRD-PARTY CALCULATED SHIPPING RATES",
        "Show calculated rates with your own account or third-party couriers",
      ],
      transaction_percentage: {
        cartalist: 1.2,
        payment_gateway: 5,
      },
    },
  ]);

  constructor() {}

  getPremadeLicenses() {
    return this.licenses$.asObservable();
  }
}
